### ISSUE TITLE
.pses folders get created in my cwd and don't get cleaned up

### ISSUE THREAD

**Issue by TylerLeonhardt** [yatli/coc-powershell#10]
We should probably move that somewhere else...

**Comment by corbob** [comment]
This should be resolved in the latest version... You may need to `:PlugUpdate` (and update your init.vim to call `coc#powershell#init`...)

The .pses should now be in the `coc-powershell` plugin folder... The logs should also be more separated if you're running multiple instances of vim.

**Comment by TylerLeonhardt** [comment]
Yes it's fixed!
