### ISSUE TITLE
Expose a function to set the powershellExecutable used

### ISSUE THREAD

**Issue by TylerLeonhardt** [yatli/coc-powershell#13]
Right now we use a global variable - but it might be more intuitive if we expose a function to set it... this function could also set it to a json file so that the value can be persisted.

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/56481606-8d908f00-6485-11e9-879b-97852d8b8233.png)

we could have it prompt too!

**Comment by yatli** [comment]
see: #14
