### ISSUE TITLE
switch between version of PS (PowerShell Core, Windows PowerShell).

### ISSUE THREAD

**Issue by yatli** [yatli/coc-powershell#23]
We can have a command like `powershell.setVersion`.

**Comment by corbob** [comment]
I **think** we have this in the configuration (contributes configuration in package.json), just not sure if the extension is actually using the configuration just yet...

**Comment by yatli** [comment]
currently in the ts client we don't yet have the code to handle that -- the configuration options are passthru to PSES directly (and then ignored, I guess)

**Comment by yatli** [comment]
I think it's definitely supported to hook up `onConfigurationChange` in coc -- will figure this out

**Comment by yatli** [comment]
done. the configuration section is fully compatible with the vscode extension, and @TylerLeonhardt has already ported the config loading code.
I've hooked up the configuration so that it is both read by our extension, and passed through to PSES.
Setting `powershell.powerShellExePath` is picked up by the extension correctly.

Tip: to edit configuration, run `:CocConfig` -- if you have `coc-json` extension it has semantic completion based on `package.json` definitions.

**Comment by TylerLeonhardt** [comment]
It still would be nice to have some sort of command/dialog for switching.
