### ISSUE TITLE
Add a prepackaged release for windows

### ISSUE THREAD

**Issue by DropBearHunta** [yatli/coc-powershell#32]
Hey there! Id love to use this extension, however I'm dealing with difficulties compiling the typescript in my companies environment due to lack of internet access, I was wondering if you could provide a release tag with a pre built package. Any help would be appreciated!

**Comment by TylerLeonhardt** [comment]
Yep we should ship this on GitHub as well. I think Azure Pipelines has a "Publish to GitHub" task

**Comment by TylerLeonhardt** [comment]
Keep in mind, #37 will have to be addressed for complete offline use

**Comment by yatli** [comment]
@DropBearHunta the bundled PSES is merged to master. Once we push this out to npm, you'll be able to download this self-contained package and copy it over to an offline machine.

**Comment by TylerLeonhardt** [comment]
Here it is! https://github.com/yatli/coc-powershell/releases/tag/v0.0.18
