### ISSUE TITLE
Can't get it to work on Ubuntu 

### ISSUE THREAD

**Issue by mikeTWC1984** [yatli/coc-powershell#34]
I installed all prereqs and followed Install guide without any error. But still can't see Intellisense/Completion while editing ps1 file. Is there any additional parameters need to be added on vimrc?

**Comment by corbob** [comment]
Since the move to TypeScript and utilizing what it gives us, I don't recall being able to get IntelliSense working on Windows either. Perhaps @TylerLeonhardt or @yatli could provide some insight on the configuration that they're using?

**Comment by yatli** [comment]
which version are you using?

**Comment by corbob** [comment]
Version of Vim? I'm using nvim 0.3.7 IIRC. I've loaded it in with `:CocInstall <Path To Cloned Repo>`

**Comment by yatli** [comment]
@corbob the installation method has changed. Now we're able to install with just `:CocInstall coc-powershell` because the package is now on npm.

**Comment by yatli** [comment]
To check whether the extension is loaded, use `:CocList extensions` -- active extensions are marked with "*"

To check the extension debug info, use `:CocInfo` and locate the output channel "powershell".

**Comment by yatli** [comment]
The latest npm package is `0.0.17` as of now

**Comment by TylerLeonhardt** [comment]
@mikeTWC1984, can you share your 
vim/NeoVim version,
node.js version,
your vimrc/init.vim

And please verify you ran `:CocInstall coc-powershell`

There was an issue with the package around the time that you filed and that should be fixed

**Comment by mikeTWC1984** [comment]
I'm using vim 8.0.1453. I'm getting same results on windows too.. 

I ran CocList extension and coc-powershell  was in "loaded" (+)  status. I changed it to enabled (*) but I didn't see any difference.

Below are steps to recreate. Installing all the stuff from scratch on the plain pwsh container. Did I miss anything?

```PowerShell
docker run -it --name vim --entrypoint pwsh mcr.microsoft.com/powershell:latest

apt install vim -y
apt install git -y
apt-install curl -y

#install node
curl -sL install-node.now.sh/lts | bash

#install vim plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim



# adding this to .vimrc

call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()


# then :PlugInstall and :CocInstall coc-powershell
# then openig some ps1 file
```

**Comment by corbob** [comment]
🤔 It seems that it took some time for the PSIC to start, but once it did, then I get auto-complete...

**Comment by TylerLeonhardt** [comment]
The first thing it does is download a dependency, PowerShell Editor Services. It takes some time.

If you also add vim-airline, you should see a message “Downloading PowerShell Editor Services…”

```
…
    Plug 'bling/vim-airline'
…

I’ve also [configured airline in my init.vim (neovim in my case)](https://gist.github.com/TylerLeonhardt/94a00f941e3aa9dcfbdb09052a883459#file-init-vim-L23-L71) which I stole from @yatli 😅

Perhaps we should think about bundling PSES with coc-powershell so initial startup doesn’t take as long…

```

**Comment by corbob** [comment]
Ah yes, it is much faster the second time around. I am using `Plug 'vim-airline/vim-airline'` for a statusline, perhaps I'll take a look at your init.vim (I have borrowed heavily from yours and @yatli in the past, might as well take another look :joy:

**Comment by yar05** [comment]
As of today running exactly the same commands as above does not work. No terminal popup and no autocomplete working in VIM

**Comment by TylerLeonhardt** [comment]
Looks like we can close this since you need vim8 and that's in our README.md :)
