### ISSUE TITLE
Consider renaming to vim-powershell?

### ISSUE THREAD

**Issue by TylerLeonhardt** [yatli/coc-powershell#4]
Just because there's https://github.com/PowerShell/vscode-powershell and vim-powershell is actually the repo name we used for the original one that shipped in CloudShell.

Just a thought. 

I'd also want to talk to https://github.com/ant-druha/powershell about calling it `intellij-powershell` 😃

We'd wanna get sign off from @corbob before the name change though - don't want to step on any toes but I think he's really interested in what you're doing in this repo 😄

**Comment by corbob** [comment]
I had a big long reply, but it was mostly rambling. So here it is: I don't own the name vim-powershell, and would be more than happy to move anything I've done there over to here assuming it moves (I'm concerned it doesn't because they're different Language Client implementations).

**Comment by TylerLeonhardt** [comment]
I just realized that all the plugins that use coc are, called `coc-*`...

In that case, we meet in the middle with `coc-powershell` 😊

**Comment by yatli** [comment]
after we settle down with this, we can talk to coc.nvim maintainer to get our plugin advertised. :D

**Comment by yatli** [comment]
done, and we are now `coc-powershell`

**Comment by yatli** [comment]
PR sent to `coc.nvim`. We can close this now;
