### ISSUE TITLE
Completion suggestion - fuzzy search

### ISSUE THREAD

**Issue by mikeTWC1984** [yatli/coc-powershell#53]
Looks like by default  auto-completion uses some fuzzy search and then sort results alphabetically. For example if I type Get-Dat, it wll list about 30 Get-AZDataLake* cmdlets first (Get-Date will be in the bottom). How to change it to use exact match (it works like that in VSCode)?

**Comment by TylerLeonhardt** [comment]
Interesting... This is definitely going to be an upstream bug in coc.nvim.

They send the completion message. VSCode is what actually sorts it properly.

Can you move this over there and maybe provide a screenshot and mention me?

**Comment by mikeTWC1984** [comment]
OK, they seemed to fix that. Closing
