### ISSUE TITLE
powershell.evaluateSelection - executes entire line, not a selection

### ISSUE THREAD

**Issue by mikeTWC1984** [yatli/coc-powershell#57]
In case if you select only some part of a single line, evaluateSelection will expand it to include entire row. For example if I only want to select and execute command in bold I'll get error:

if ( **test-path  ./somefile**) {
  ....
}

Can we tweak it to run selection only?

**Comment by TylerLeonhardt** [comment]
Yes, this looks like a bug. Thanks!

**Comment by TylerLeonhardt** [comment]
Fix incomming! https://github.com/yatli/coc-powershell/pull/60
