### ISSUE TITLE
No handler registered for Request type 'powershell/getCommand'

### ISSUE THREAD

**Issue by corbob** [yatli/coc-powershell#7]
I'm trying to mimic some of the things we do in vscode-powershell, to get my feet wet with how the Language Client works. I think I need to call CocRequestAsync (or not Async, but really, should be Async...). When I try the only thing I'm getting in the log is:

```
2019-04-17 22:22:26.612 [VERBOSE] tid:18 in 'ReadMessage' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs: line 138
    Received Request 'powershell/getCommand' with id 2

    {
      "jsonrpc": "2.0",
      "id": 2,
      "method": "powershell/getCommand",
      "params": "get-help"
    }

2019-04-17 22:22:26.612 [WARNING] tid:18 in 'DispatchMessage' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs: line 134
    MessageDispatcher: No handler registered for Request type 'powershell/getCommand'
```

The steps to reproduce are:

```vimL
" Either add this to init.vim/vimrc or otherwise create the function.
function! CallBack(a) abort
    echo a:a
endfunction
```
Call the Requestion function:
`:call CocRequestAsync('pses', 'powershell/getCommand', 'get-help', function('CallBack'))`

The 'powershell/getCommand' message sent to PSES when given a parameter should return information about the command.

Is this a case of needing to register the request type with coc.nvim or coc-pses?

**Comment by yatli** [comment]
the log appears to be complaining about the PSES side not having a handler for 'getCommand', not the coc side.

Note 'powershell/..' prefix is sent to PSES. I guess this is the issue?

**Comment by corbob** [comment]
🤔 that's certainly a possibility. In vscode-powershell, it's definitely the request we report we're setting, and I could have sworn I matched it up on the PSES side. I'll have a look at that. I did realize that evaluate is an option, so I tried it with that, and it's definitely sending and executing as expected. It just seems that it's not triggering the callback function.

I guess I need to figure out what it's doing and how to actually specify the callback function (it would seem it's not calling it the way LanguageClient did)

**Comment by yatli** [comment]
how about:

`:call CocRequestAsync('pses', 'getCommand', 'get-help', function('CallBack'))`

(layman's idea!)

**Comment by yatli** [comment]
an alternative:

@corbob if you're comfortable with Typescript, take a look here:

https://github.com/neoclide/coc-rls/tree/master/src

It's a coc wrapper for the rust lsp server binary.
You can basically wrap up a console version of VSCode in the ts world.

**Comment by yatli** [comment]
linking #17
